version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install

workflows:
  deploy:
    jobs:
      - build
